### ISSUE TITLE
Login Page: Add title, maybe information

### ISSUE THREAD

**Issue by booherbg** [Grand-Farm/Partner-Management#2]

**Comment by booherbg** [comment]
- Add title, maybe a little paragraph on who should be registering, etc.
- Add some heirarchy to the button (flat and blends w/ background)
- Align the text boxes so that they're at the same left position (divs around the labels works fine) or just use bootstrap for control groups

**Comment by levimastrud** [comment]
Both login and registration pages have been given more context and styled to look better.
