### ISSUE TITLE
Grand Farm Landing Page: Add some context for what this website is (title, something like that)

### ISSUE THREAD

**Issue by booherbg** [Grand-Farm/Partner-Management#3]
- Add some context for what this website is (title, something like that)
- Stretch Goal: Consider showing project widgets OR just show projects here

**Comment by levimastrud** [comment]
Cleaned up landing page and added a '?' widget for getting more info.

**Comment by levimastrud** [comment]
Cleaned up landing page and added a '?' widget for getting more info.
